volatile uint8_t ui8Adjust; //VARIABLE FOR PWM_WIDTH SET AS % FROM 0 TO 100
//CLOCK SETTINGS - SET SYSTEM CLOCK TO 40MHz
SysCtlClockSet(SYSCTL_SYSDIV_5|SYSCTL_USE_PLL|SYSCTL_OSC_MAIN|SYSCTL_XTAL_16MHZ);
//SET PWM CLOCK AS SYSTEM CLOCK DIVIDED BY 64
SysCtlPWMClockSet(SYSCTL_PWMDIV_64);
//PERIPHERAL CONFIGURATION
SysCtlPeripheralEnable(SYSCTL_PERIPH_PWM1); //PWM PERIPHERAL ENABLE
SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD); //GPIO FOR PWM1
GPIOPinTypePWM(GPIO_PORTD_BASE, GPIO_PIN_0); //GPIO PD0 FOR PWM1
GPIOPinConfigure(GPIO_PD0_M1PWM0); //PD0 AS M1PWM0
PWMGenConfigure(PWM1_BASE, PWM_GEN_0, PWM_GEN_MODE_DOWN);
//SET PWM GENERATOR WITH MODEOF OPERATION AS COUNTING
PWMGenPeriodSet(PWM1_BASE, PWM_GEN_0,100); //SET PERIOD OF PWM GENERATOR
PWMOutputState(PWM1_BASE, PWM_OUT_0_BIT, true); //ENABLE BIT0 OUTPUT
PWMGenEnable(PWM1_BASE, PWM_GEN_0); //ENABLE PWM_GEN_0 GENERATOR
